name: deeply_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: any
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.3
  provider: ^6.1.1
  get_it: ^7.6.4
  audioplayers: ^5.2.1
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  record: ^4.4.4
  flutter_sound_lite: ^8.5.0
  audio_waveforms: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.9
  flutter_automation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: "^0.13.1" # AjoutÃ© ici
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F2F6DB" # La couleur de fond du splash screen
  image: assets/images/launch_screen.png # Le chemin vers l'image du splash screen
  android: true # Active le splash screen pour Android
  ios: true # Active le splash screen pour iOS

  android_12:
    image: assets/images/launch_screen.png # Le chemin vers l'image du splash screen pour Android 12 et plus
    color: "#F2F6DB" # La couleur de fond du splash screen pour Android 12 et plus



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/questions/
    - assets/links/
    - assets/icon/

  fonts:
    - family: PlayfairDispaly
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
    - family: PlayfairDispalyNormal
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf